packages:
  - 'packages/*'
  - 'libs/*'
  - 'apps/*'
  - 'apps/web/*'
  - 'graphql-sdk'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - 'core-js'
  - 'esbuild'
  - 'nx'
